### ISSUE TITLE
Stage already visible

### ISSUE THREAD

**Issue by TheRedSpy15** [TheRedSpy15/The-Trail#39]
Exception: 

```
Exception in thread "JavaFX Application Thread" java.lang.IllegalStateException: Stage already visible
	at javafx.stage.Stage.showAndWait(Stage.java:460)
	at com.TheRedSpy15.trail.HealthClass.poorHealthEvent(HealthClass.java:111)
	at com.TheRedSpy15.trail.HealthClass.determineHealthCondition(HealthClass.java:79)
	at com.TheRedSpy15.trail.TravelController.lambda$null$0(TravelController.java:119)
	at com.sun.javafx.application.PlatformImpl.lambda$null$173(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$174(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$null$148(WinApplication.java:191)
	at java.lang.Thread.run(Thread.java:748)

	Exception in thread "JavaFX Application Thread" java.lang.IllegalStateException: Stage already visible
	at javafx.stage.Stage.showAndWait(Stage.java:460)
	at com.TheRedSpy15.trail.HealthClass.poorHealthEvent(HealthClass.java:128)
	at com.TheRedSpy15.trail.HealthClass.determineHealthCondition(HealthClass.java:79)
	at com.TheRedSpy15.trail.TravelController.lambda$null$0(TravelController.java:120)
	at com.sun.javafx.application.PlatformImpl.lambda$null$173(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$174(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.win.WinApplication._enterNestedEventLoopImpl(Native Method)
	at com.sun.glass.ui.win.WinApplication._enterNestedEventLoop(WinApplication.java:218)
	at com.sun.glass.ui.Application.enterNestedEventLoop(Application.java:511)
	at com.sun.glass.ui.EventLoop.enter(EventLoop.java:107)
	at com.sun.javafx.tk.quantum.QuantumToolkit.enterNestedEventLoop(QuantumToolkit.java:583)
	at javafx.stage.Stage.showAndWait(Stage.java:474)
	at com.TheRedSpy15.trail.HealthClass.poorHealthEvent(HealthClass.java:128)
	at com.TheRedSpy15.trail.HealthClass.determineHealthCondition(HealthClass.java:79)
	at com.TheRedSpy15.trail.TravelController.lambda$null$0(TravelController.java:120)
	at com.sun.javafx.application.PlatformImpl.lambda$null$173(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$174(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$null$148(WinApplication.java:191)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by TheRedSpy15** [comment]
I'm thinking, making the getter for the alert stage synchronized, and/or the stage itself volatile, may help
